[workspace]
members = [
  "coordinator",
  "prover"
]

[profile.release]
opt-level = 3
lto = "thin"

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git = "https://github.com/smtmfft/halo2.git", rev = "5fc8ce89ef3235d8eefeb8994173ac706e89e4ec", package = "halo2_proofs" }
